language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - curl -sS http://getcomposer.org/installer | php -d hhvm.resource_limit.socket_default_timeout=120
  - php composer.phar install --dev

script: phpunit
